moved back to include 'mpif.h' due to error in GCC 13
Error: There is no specific subroutine for the generic ‘mpi_allreduce’  due to mpi not handling 64 bit count variable